Feature/mt 7 topic2 home work
batonkarton/MentoAD pull request #3
Opened 2024-10-07 17:50 UTC by AliakseiDziardziyashenka

2024-10-08 07:54 UTC, batonkarton commented
@AliakseiDziardziyashenka let's make one more clean up. 
The folder structure for MentoAD.sln should be as follows:
- MentoAD(repository folder)
  - .github(folder)
  - MentoringHomeWork(folder) - MentoAD.sln should be in this folder (.sln and .csproj files should be in separate folders)
    - HW2 - here you can place your .csproj
      - HW2.0
      - HW2.1

2024-10-08 07:56 UTC, batonkarton commented
Now you can merge actual changes from the main branch using GitHub UI:
![image](https://github.com/user-attachments/assets/05f45b2f-e337-446b-8a38-6fe0852ccf1f)

2024-10-08 08:00 UTC, batonkarton requested changes

2024-10-08 08:00 UTC, batonkarton commented on .idea/indexLayout.xml
Remove .idea folder

2024-10-08 08:00 UTC, batonkarton commented on MentoAD/.idea/.idea.MentoAD/.idea/.gitignore
Remove .idea folder

2024-10-08 08:00 UTC, batonkarton commented on MentoAD/HW2/HW2.0/HW2.cs
> +
Remove these whitespaces - let's talk about code style conventions next time - I will prepare a confluence doc about it.

2024-10-08 08:00 UTC, batonkarton commented on MentoAD/HW2/HW2.0/HW2.cs
> +
The same.

2024-10-10 16:49 UTC, batonkarton commented on .idea/indexLayout.xml
Resolved.

2024-10-13 16:59 UTC, AliakseiDziardziyashenka commented on MentoAD/.idea/.idea.MentoAD/.idea/.gitignore
Ready for review

2024-10-13 18:12 UTC, batonkarton approved these changes

2024-10-13 18:13 UTC, merged